# Site
repository: seunghkong/resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Seung Hyun Kong
title: Platform Developer
email: seunghkong@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  seunghkong
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: seunghkong
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
# about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I have experience not only developing tools with python and golang, but also with deploying apps to kubernetes in AWS.

  I have designed and managed the infrastructure needed to host translations and chat filter service that served 300k concurrent users
  with latency within the 200ms threshold.

  For the benefit of my team, I have self-managed an elk stack in the private cloud to collect all logs and metrics from
  services for internal use for tracking issues and collect statistics.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Ncsoft
        link: ncsoft.com
        link_text: ncsoft.com
        sub_title: Platform Developer
        caption: January 2022 - Present
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          - Chatbot - service deployment, logging
          - Digital Human - managed environment, deployment, logging
          - Spam Detection - Maintained legacy code, deployment

  - title: Projects # Title for the section
    layout: list
    content:
      - layout: top-middle
        title: Infra Management
        # caption: 2023
        description: | # this will include new lines to allow paragraphs
          - (2024.05~) Managed docker container security vulnerabilities for services in production
          - (2024.01~) Managed spam filter and translation service for 300k concurrent users for TL global
          - (2023~) Managed healthcheck standards for deployments for seamless rolling and zero downtime deployment
          - (2022~) Stress tested deployments for cost efficient HPA configuration
      - layout: top-middle
        title: Devops
        # caption: 2023
        description: | # this will include new lines to allow paragraphs
          - (2024.01~2024.05) Developed controller for chatbots 
          - (2023~) Managed continuous deployment to kubernetes clusters for dev/prod
          - (2022~) Developed and managed CI with gitlab-ci for researchers
      - layout: top-middle
        title: Logging
        # caption: 2022/05~
        description: | # this will include new lines to allow paragraphs
          - (2023~) Installed and managed ELK stack for collecting all internal services
          - Unified log format and guide for internal deployments
          - Improved logging architecture in kubernetes deployments
  
  - title: Stack # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: DevOps
        # link: github.com/sproogen
        # link_text: Project Website
        description: | # this will include new lines to allow paragraphs
          - gitlab-ci, argocd
          - <mark>AWS</mark> Elasticache, RDS, S3, EKS, Opensearch, EC2
          - MySQL, Elasticsearch
          - docker, kubernetes, helm
          - nginx
          - locust
          - linux ubuntu, (ba)sh

      - layout: left
        title: Backend
        # link: github.com/sproogen
        # link_text: Project Website
        description: | # this will include new lines to allow paragraphs
          - golang, python
          - golang echo, fastapi
          - redis, mysql, elasticsearch
          - vscode, nvim

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Korea University
        caption: 2016 - 2022
        sub_title: BSc Computer Science
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        # description: | # this will include new lines to allow paragraphs
          # While learning about essential skills like teamwork and  

  - title: Certifications
    layout: list
    content: 
      - layout: top-middle
        title:  Professional Cloud Architect Certification
        link: https://www.credly.com/badges/036fea52-a615-4b56-858c-7c4f907bc268/linked_in_profile
        link_text: Show credential 
        sub_title: Google
        Caption: Issued Jun 2024

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      I am fluent in both korean and english.
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Bouldering
      - Gaming
      - Baking

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
